### ISSUE TITLE
Please update url-parse dependency

### ISSUE THREAD

**Issue by Rogach** [unshiftio/original#21]
Currently `original` depends on `url-parse` version `1.0.x`, and that version is listed as vulnerable and npm audit complains: https://www.npmjs.com/advisories/678

Can the dependency be updated to newer `url-parse`?

**Comment by lpinca** [comment]
https://github.com/unshiftio/original/blob/3a6b7dfc741587920f0cdd3aebe4e589bff0f7d3/package.json#L25

**Comment by Rogach** [comment]
I'm terribly sorry, that was a huge oversight on my part - I was looking on the wrong version. Thank you!

**Comment by tamas-nemeth** [comment]
there have been later vulnerabilities in `url-parse` as well
https://snyk.io/vuln/npm:url-parse

the version of `url-parse` in `package.json` has been updated, however `original` has not been released since then
https://github.com/unshiftio/original/commit/6e95ccee8cb868a3c7553304bec01ad97e2487fa

could you please publish a release to npm?

**Comment by lpinca** [comment]
See https://github.com/unshiftio/original/issues/21#issuecomment-504417768. That version range already covers the latest version of `url-parse`.
